<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblio [
 <!ELEMENT biblio (livre)+>
 <!ELEMENT livre (titre+,auteur,nombre)>
 <!ELEMENT titre (#PCDATA) >
 <!ELEMENT auteur (#PCDATA) >
 <!ELEMENT nombre (#PCDATA) >
 <!ATTLIST livre etat  (neuf | mauvais | moyen) #REQUIRED
langue CDATA #IMPLIED>
 ]>
<biblio>
<livre etat="mauvais" langue="francais">
<titre>Programmer en langage C</titre>
<auteur>Claude Delannoy</auteur>
<nombre>275</nombre>
</livre>
<livre etat="neuf">
<titre >Programmer en langage Java</titre>
<auteur>Claude Delannoy</auteur>
<nombre>677</nombre>
</livre>
<livre etat ="moyen">
<titre>Javascript</titre>
<auteur>Francais Pellerin</auteur>
<nombre>155</nombre>
</livre>
<livre etat="neuf" langue="francais">
<titre >Developpement logiciel</titre>
<auteur>Jean-Francois Pillou</auteur>
<nombre>227</nombre>
</livre>
</biblio>